name: libgfx
description: A comprehensive 2D vector graphics engine for Dart with software rasterization, supporting paths, strokes, gradients, text, and advanced rendering features.
version: 1.0.3
repository: https://github.com/libdbm/libgfx
homepage: https://github.com/libdbm/libgfx
documentation: https://github.com/libdbm/libgfx#readme
issue_tracker: https://github.com/libdbm/libgfx/issues
license: BSD-3-Clause

topics:
  - graphics
  - vector
  - drawing

environment:
  sdk: ^3.8.1

dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
